encoding = "utf-8"

[http]
host = "0.0.0.0"
port = 8011

[http.public]
host = "fuziondev"
port = 8182
secure = true

[logging]
log_to_stdout = true
log_level = "info"

[database]
host = "127.0.0.1"
port = 8432
user = "fuzion"
password = "CHANGEME"
name = "fuzion"
